<a href="https://colab.research.google.com/github/DarkLyng/Challenge-TelecomX_P2/blob/main/Telecom_X_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🛠️ Preparación de los Datos**

In [14]:
#Bibliotecas

import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
datos = pd.read_csv("/content/df_normalizado.csv")
datos

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,0,Female,0,1,1,9,1,0,DSL,...,1,0,1,1,0,One year,1,Mailed check,65.60,593.30
1,0003-MKNFE,0,Male,0,0,0,9,1,1,DSL,...,0,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40
2,0004-TLHLJ,1,Male,0,0,0,4,1,0,Fiber optic,...,0,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85
3,0011-IGKFF,1,Male,1,1,0,13,1,0,Fiber optic,...,1,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85
4,0013-EXCHZ,1,Female,1,1,0,3,1,0,Fiber optic,...,0,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,9987-LUTYD,0,Female,0,0,0,13,1,0,DSL,...,0,0,1,0,0,One year,0,Mailed check,55.15,742.90
7028,9992-RRAMN,1,Male,0,1,0,22,1,1,Fiber optic,...,0,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70
7029,9992-UJOEL,0,Male,0,0,0,2,1,0,DSL,...,1,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75
7030,9993-LHIEB,0,Male,0,1,1,67,1,0,DSL,...,0,1,1,0,1,Two year,0,Mailed check,67.85,4627.65
7031,9995-HOTOH,0,Male,0,1,1,63,0,0,DSL,...,1,1,0,1,1,Two year,0,Electronic check,59.00,3707.60

In [16]:
#Eliminar columnas que no aportan valor al análisis
datos = datos.drop("customerID", axis=1 )
datos.head()

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
2097,0,Female,0,1,1,7,1,0,0,0,0,0,0,0,0,Month-to-month,0,Mailed check,20.65,158.95
5584,0,Female,0,1,1,69,1,0,0,0,0,0,0,0,0,Two year,0,Credit card (automatic),19.80,1436.95
4768,0,Female,1,1,0,71,1,0,Fiber optic,0,1,1,0,0,1,Two year,0,Credit card (automatic),89.45,6435.25
3200,0,Female,0,0,0,53,0,0,DSL,1,1,1,1,1,0,One year,1,Electronic check,53.60,2879.20
2956,0,Male,0,0,0,1,1,0,0,0,0,0,0,0,0,Month-to-month,0,Electronic check,19.20,19.20
2772,0,Male,0,0,0,20,1,0,Fiber optic,0,0,0,0,1,0,Month-to-month,0,Electronic check,78.80,1641.30
3588,1,Male,1,1,1,43,1,1,Fiber optic,0,1,1,1,1,1,Month-to-month,1,Bank transfer (automatic),110.75,4687.90
3981,0,Female,0,0,0,20,1,1,Fiber optic,1,0,0,0,1,0,Month-to-month,1,Bank transfer (automatic),89.10,1879.25
6301,0,Male,0,0,0,68,1,1,DSL,1,1,1,0,0,1,One year,0,Credit card (automatic),76.75,5233.25
153,0,Male,0,1,0,52,1,1,DSL,1,1,1,1,0,1,One year,1,Credit card (automatic),81.40,4354.45

# **Verificacion de la proporción de cancelación**

In [21]:
datos["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [22]:
datos["Churn"].value_counts(normalize=True)*100

Churn
0    73.421502
1    26.578498
Name: proportion, dtype: float64